spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meethere?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      #更新或创建数据表结构
      ddl-auto: update
      #控制台显示SQL语句
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQLInnoDBDialect
server:
  port: 8083

